import Link from "next/link";
import { redirect } from "next/navigation";
import { Activity, ArrowLeft, ArrowRight, CalendarDays, Download, Filter, Flag, Info, LockKeyhole, Search, Trophy, Users2 } from "lucide-react";
import type { ReactNode } from "react";

import { getAdminAccessState } from "@/lib/admin";
import { getAdminAnalyticsData } from "@/server/admin-analytics";
import type { AdminAnalyticsData } from "@/lib/admin-analytics";

export const dynamic = "force-dynamic";

type SearchParams = Record<string, string | string[] | undefined>;
const numberFormat = new Intl.NumberFormat("ru-RU");
const dateFormat = new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" });
const timeFormat = new Intl.DateTimeFormat("ru-RU", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit", timeZone: "UTC" });
const panelClass = "rounded-2xl border border-black/10 bg-white p-4 shadow-sm sm:p-6";
const inputClass = "h-11 w-full rounded-lg border border-black/15 bg-white px-3 text-sm text-ink focus:border-court focus:outline-none focus:ring-2 focus:ring-court/20";

export default async function AdminAnalyticsPage({ searchParams = {} }: { searchParams?: SearchParams }) {
  const access = await getAdminAccessState();
  if (!access.user) redirect(`/auth?continue=${encodeURIComponent("/admin/analytics")}&step=email`);
  if (!access.configured || !access.isAdmin) {
    return <main className="mx-auto max-w-xl px-4 py-16"><div className={panelClass}><LockKeyhole className="h-7 w-7 text-court" /><h1 className="mt-4 text-2xl font-bold">Доступ ограничен</h1><p className="mt-3 text-sm text-ink/65">Аналитика приложения доступна только администраторам.</p><Link href="/admin" className="mt-5 inline-block font-semibold text-court">В операционную панель</Link></div></main>;
  }
  const data = await getAdminAnalyticsData({ days: Number(first(searchParams.days)) || undefined, userId: first(searchParams.userId), eventType: first(searchParams.eventType), page: Number(first(searchParams.page)) || undefined });
  const filters = data.filters;
  const worstStep = data.funnel.slice(1).reduce<(typeof data.funnel)[number] | null>((worst, step) => step.dropOff > (worst?.dropOff ?? 0) ? step : worst, null);

  return <main className="min-h-screen bg-[#f7f5ef] px-4 py-6 text-ink sm:py-8">
    <div className="mx-auto max-w-7xl space-y-5">
      <Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-ink/60 hover:text-court"><ArrowLeft className="h-4 w-4" /> Операционная панель</Link>
      <header className="overflow-hidden rounded-2xl bg-ink p-5 text-white sm:p-8">
        <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between">
          <div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-white/60"><Activity className="h-4 w-4" /> Аналитика продукта</div><h1 className="mt-3 text-2xl font-bold leading-tight sm:text-4xl">От регистрации до первой игры</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/65">Следите за конверсией, находите этапы с потерями и изучайте действия игроков.</p></div>
          <div className="shrink-0 text-xs leading-6 text-white/60"><div>Обновлено {timeFormat.format(data.generatedAt)} UTC</div><div>{dateFormat.format(data.period.from)} — {dateFormat.format(data.period.to)}</div></div>
        </div>
        <div className="mt-6 flex flex-wrap items-center gap-2 border-t border-white/10 pt-5"><CalendarDays className="mr-1 h-4 w-4 text-white/60" /><span className="mr-2 text-sm text-white/70">Период</span>{([7, 30, 90] as const).map(days => <Link key={days} href={analyticsHref({ ...filters, days, page: 1 })} aria-current={filters.days === days ? "page" : undefined} className={`rounded-lg px-4 py-2 text-sm font-semibold transition ${filters.days === days ? "bg-white text-ink" : "bg-white/10 text-white/80 hover:bg-white/20"}`}>{days} дней</Link>)}<span className="ml-auto text-xs text-white/50">Все даты и границы дней — UTC</span></div>
      </header>

      <nav aria-label="Разделы аналитики" className="flex gap-2 overflow-x-auto pb-1 text-sm font-semibold">{[["funnel", "Воронка"], ["dynamics", "Динамика"], ["events", "События"], ["journal", "Журнал действий"]].map(([id, title]) => <a key={id} href={`#${id}`} className="whitespace-nowrap rounded-lg border border-black/10 bg-white px-4 py-2.5 hover:border-court/40 hover:text-court">{title}</a>)}</nav>
      <section aria-label="Ключевые показатели" className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <Metric icon={<Users2 className="h-5 w-5" />} label="Новые игроки" value={numberFormat.format(data.metrics.newUsers)} description="Зарегистрировались за выбранный период" />
        <Metric icon={<Activity className="h-5 w-5" />} label="Активные игроки" value={numberFormat.format(data.metrics.activeUsers)} description="Уникальные игроки с активными действиями за период" />
        <Metric icon={<Flag className="h-5 w-5" />} label="Конверсия в первую игру" value={percent(data.metrics.registrationToGameRate)} description={`${numberFormat.format(data.metrics.playedUsers)} из ${numberFormat.format(data.metrics.newUsers)} новых игроков; по данным игр`} accent />
        <Metric icon={<Trophy className="h-5 w-5" />} label="Сыгранные игры" value={numberFormat.format(data.metrics.playedGames)} description="Все игры с отметкой «сыграли» за период" />
      </section>

      <section className="rounded-xl border border-amber-900/10 bg-[#faf0da] px-4 py-4 text-sm leading-6 text-ink/75" aria-label="Полнота данных"><div className="flex items-start gap-3"><Info className="mt-1 h-4 w-4 shrink-0" /><div><p className="font-semibold text-ink">Как читать данные</p><p>Журнал доступен {data.coverage.firstEventAt ? `с ${dateFormat.format(data.coverage.firstEventAt)}` : "после первых записанных действий"}. События воронки: {data.coverage.firstFunnelEventAt ? `с ${dateFormat.format(data.coverage.firstFunnelEventAt)}` : "пока не накоплены"}.</p><p className="mt-1">История до начала сбора не восстановлена. Воронка учитывает только записанные шаги и может быть ниже фактической конверсии.</p><details className="mt-2"><summary className="cursor-pointer font-semibold text-ink">Определения метрик и ограничения данных</summary><div className="mt-2 space-y-2">{data.coverage.notes.map((note, i) => <p key={i}>{note}</p>)}</div></details><p className="mt-1">В веб-приложении собираются открытия приложения, просмотры подбора игроков и вход в онбординг. Успешные действия на сервере учитываются для веб-приложения и iOS. Новым игрокам нужно время, чтобы пройти все этапы.</p></div></div></section>

      <section id="funnel" className={`${panelClass} scroll-mt-5`}>
        <SectionHeader title="Воронка первой игры" description="Когорта — игроки, зарегистрировавшиеся в выбранный период. Каждый следующий этап учитывается после предыдущего; один игрок считается один раз." />
        {data.funnel.length === 0 ? <Empty text="Для воронки пока недостаточно данных." /> : <div className="mt-5 space-y-3">{data.funnel.map((step, index) => <div key={step.key} className="grid gap-3 rounded-xl border border-black/10 p-4 lg:grid-cols-[minmax(200px,1fr)_minmax(180px,1.1fr)_minmax(200px,1fr)] lg:items-center"><div className="flex items-center gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-cream text-sm font-bold text-court">{index + 1}</span><div><div className="text-sm font-semibold">{step.label}</div><div className="mt-1 text-2xl font-bold">{numberFormat.format(step.users)} <span className="text-xs font-normal text-ink/50">игроков</span></div></div></div><div><div className="h-3 overflow-hidden rounded-full bg-cream"><div className="h-full rounded-full bg-[#126A4A]" style={{ width: `${clampPercent(step.conversionFromRegistration)}%` }} /></div><p className="mt-2 text-xs text-ink/55">{percent(step.conversionFromRegistration)} от регистраций</p></div><div className="grid grid-cols-2 gap-3 text-sm lg:text-right"><div><div className="font-bold">{index === 0 ? "—" : percent(step.conversionFromPrevious)}</div><div className="mt-1 text-xs text-ink/50">от предыдущего этапа</div></div><div><div className={index > 0 && step.dropOff > 0 ? "font-bold text-amber-800" : "font-bold"}>{index === 0 ? "—" : numberFormat.format(step.dropOff)}</div><div className="mt-1 text-xs text-ink/50">не перешли дальше</div></div></div></div>)}</div>}
        {worstStep && <div className="mt-4 flex items-start gap-3 rounded-xl bg-cream p-4 text-sm leading-6"><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-court" /><p>Больше всего игроков пока не дошли до этапа <strong>«{worstStep.label}»</strong>: {numberFormat.format(worstStep.dropOff)}. Изучите их действия в журнале, чтобы проверить причину.</p></div>}
        <p className="mt-4 text-xs leading-5 text-ink/55">Воронка показывает записанную последовательность шагов; ее итог может быть ниже фактической конверсии в карточке выше при неполной истории. Сыгранная игра — результат «сыграли», отмеченный в приложении. Мэтч и договоренность сами по себе не означают состоявшуюся игру. «Не перешли дальше» включает игроков, которые еще проходят этот путь.</p>
      </section>

      <section id="dynamics" className={`${panelClass} scroll-mt-5`}><SectionHeader title="Динамика по дням" description="Первая игра — число игроков, впервые отметивших сыгранную игру в этот день. Одна игра может быть первой у двух участников. Активность считается по действиям за день." /><DailyChart daily={data.daily} /><details className="mt-5"><summary className="cursor-pointer text-sm font-semibold text-court">Точные значения по дням</summary><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[540px] text-left text-sm"><thead><tr className="border-b border-black/10 text-xs text-ink/50">{["Дата, UTC", "Регистрации", "Активные игроки", "События", "С первой игрой"].map(label => <th key={label} className="px-2 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{data.daily.map(day => <tr key={day.day} className="border-b border-black/5"><td className="px-2 py-2">{day.day}</td>{[day.registrations, day.activeUsers, day.events, day.firstGames].map((value, index) => <td key={index} className="px-2 py-2 tabular-nums">{numberFormat.format(value)}</td>)}</tr>)}</tbody></table></div></details></section>

      <section id="events" className={`${panelClass} scroll-mt-5`}><SectionHeader title="Какие действия совершают игроки" description={`${numberFormat.format(data.metrics.totalEvents)} событий за выбранный период. Количество событий может включать повторные действия одного игрока.`} />{data.eventBreakdown.length === 0 ? <Empty text="Событий за этот период пока нет. После действий игроков здесь появится статистика." /> : <div className="mt-4 grid gap-2 md:grid-cols-2">{data.eventBreakdown.map(event => <Link key={event.type} href={`${analyticsHref({ ...filters, eventType: event.type, userId: "", page: 1 })}#journal`} className="flex items-center justify-between gap-4 rounded-xl border border-black/10 px-4 py-3 hover:border-court/40"><div className="min-w-0"><div className="text-sm font-semibold">{event.label}</div><div className="mt-1 text-xs text-ink/50">{numberFormat.format(event.users)} уникальных игроков</div></div><div className="flex items-center gap-2"><strong className="text-lg tabular-nums">{numberFormat.format(event.count)}</strong><ArrowRight className="h-4 w-4 text-court" /></div></Link>)}</div>}</section>

      <section id="journal" className={`${panelClass} scroll-mt-5`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><SectionHeader title="Журнал действий" description="Фильтры игрока и типа события применяются только к журналу и выгрузке. Показатели выше относятся ко всему приложению." /><a href={exportHref(filters)} className="inline-flex h-11 shrink-0 items-center justify-center gap-2 rounded-lg bg-[#126A4A] px-4 text-sm font-semibold text-white hover:bg-[#0e573d]"><Download className="h-4 w-4" /> Скачать CSV</a></div>
        <form action="/admin/analytics#journal" method="get" className="mt-5 grid gap-3 rounded-xl bg-cream p-4 md:grid-cols-[1fr_1fr_auto] md:items-end"><input type="hidden" name="days" value={filters.days} /><label className="block text-xs font-semibold text-ink/60">Игрок (точный ID)<input name="userId" defaultValue={filters.userId} placeholder="Все игроки" className={`${inputClass} mt-2`} maxLength={200} /></label><label className="block text-xs font-semibold text-ink/60">Действие<select name="eventType" defaultValue={filters.eventType} className={`${inputClass} mt-2`}><option value="">Все действия</option>{filters.eventType && !data.eventBreakdown.some(event => event.type === filters.eventType) && <option value={filters.eventType}>{filters.eventType}</option>}{data.eventBreakdown.map(event => <option key={event.type} value={event.type}>{event.label}</option>)}</select></label><button type="submit" className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-ink px-5 text-sm font-semibold text-white"><Filter className="h-4 w-4" /> Применить</button></form>
        <p className="mt-3 text-xs leading-5 text-ink/55">Можно выбрать игрока нажатием на имя в журнале или открыть историю из его карточки. <Link href="/admin/players" className="font-semibold text-court underline decoration-court/30">Найти игрока по имени или email</Link></p>
        <div className="mt-3 flex flex-wrap justify-between gap-2 text-xs text-ink/55"><span>Найдено {numberFormat.format(data.journal.total)} событий · CSV: до 10 000 последних событий</span>{(filters.userId || filters.eventType) && <Link href={`${analyticsHref({ days: filters.days })}#journal`} className="font-semibold text-court">Сбросить фильтры журнала</Link>}</div>
        {data.journal.items.length === 0 ? <Empty text="По этим фильтрам действий нет. Измените период или сбросьте фильтры журнала." /> : <div className="mt-4 divide-y divide-black/10">{data.journal.items.map(event => <article key={event.id} className="grid gap-3 py-4 lg:grid-cols-[115px_minmax(170px,0.85fr)_minmax(210px,1fr)_minmax(180px,1fr)]"><time dateTime={event.createdAt.toISOString()} className="text-xs leading-6 tabular-nums text-ink/55">{timeFormat.format(event.createdAt)} UTC</time><div className="min-w-0"><Link href={`${analyticsHref({ ...filters, userId: event.userId, page: 1 })}#journal`} className="break-words text-sm font-semibold text-court hover:underline">{event.userName || event.userEmail}</Link><div className="mt-1 break-all text-xs text-ink/50">{event.userEmail}</div><Link href={`/admin/players/${encodeURIComponent(event.userId)}`} className="mt-1 inline-block text-xs text-ink/50 underline decoration-black/20">Карточка игрока</Link></div><div><div className="text-sm font-semibold">{event.label}</div><div className="mt-1 break-all text-xs text-ink/45">{event.type}</div>{event.entityId && <div className="mt-1 break-all text-xs text-ink/45">{event.entityType ?? "Объект"}: {event.entityId}</div>}</div><div className="flex flex-wrap content-start gap-1">{safeContext(event.context).map(([key, value]) => <span key={key} className="max-w-full break-words rounded-md bg-cream px-2 py-1 text-xs text-ink/65">{key}: {value}</span>)}</div></article>)}</div>}
        {data.journal.totalPages > 1 && <nav aria-label="Страницы журнала" className="mt-5 flex items-center justify-between gap-2 border-t border-black/10 pt-4">{data.journal.page > 1 ? <Link href={`${analyticsHref({ ...filters, page: data.journal.page - 1 })}#journal`} className="rounded-lg border border-black/10 px-3 py-2 text-sm font-semibold">Назад</Link> : <span />}<span className="text-xs text-ink/55">Страница {data.journal.page} из {data.journal.totalPages}</span>{data.journal.page < data.journal.totalPages ? <Link href={`${analyticsHref({ ...filters, page: data.journal.page + 1 })}#journal`} className="rounded-lg border border-black/10 px-3 py-2 text-sm font-semibold">Дальше</Link> : <span />}</nav>}
      </section>
    </div>
  </main>;
}

function first(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] ?? "" : value ?? ""; }
function percent(value: number | null) { return value === null || !Number.isFinite(value) ? "—" : `${new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 1 }).format(value)}%`; }
function clampPercent(value: number | null) { return Number.isFinite(value) ? Math.min(100, Math.max(0, value ?? 0)) : 0; }
function analyticsHref(filters: { days: number; userId?: string; eventType?: string; page?: number }) { const query = new URLSearchParams({ days: String(filters.days) }); if (filters.userId) query.set("userId", filters.userId); if (filters.eventType) query.set("eventType", filters.eventType); if (filters.page && filters.page > 1) query.set("page", String(filters.page)); return `/admin/analytics?${query.toString()}`; }
function exportHref(filters: AdminAnalyticsData["filters"]) { return analyticsHref({ ...filters, page: 1 }).replace("/admin/analytics?", "/api/admin/analytics/export?"); }
function SectionHeader({ title, description }: { title: string; description: string }) { return <div><h2 className="text-lg font-bold sm:text-xl">{title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-ink/60">{description}</p></div>; }
function Metric({ icon, label, value, description, accent = false }: { icon: ReactNode; label: string; value: string; description: string; accent?: boolean }) { return <div className={`rounded-2xl border p-5 ${accent ? "border-court/20 bg-[#126A4A] text-white" : "border-black/10 bg-white"}`}><div className={`flex items-center justify-between gap-2 text-sm ${accent ? "text-white/75" : "text-ink/55"}`}><span>{label}</span>{icon}</div><div className="mt-4 text-3xl font-bold tabular-nums">{value}</div><p className={`mt-2 text-xs leading-5 ${accent ? "text-white/65" : "text-ink/50"}`}>{description}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="mt-5 rounded-xl border border-dashed border-black/15 bg-cream/40 px-5 py-9 text-center"><Search className="mx-auto h-6 w-6 text-ink/25" /><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-ink/55">{text}</p></div>; }
function DailyChart({ daily }: { daily: AdminAnalyticsData["daily"] }) {
  const max = Math.max(1, ...daily.flatMap(day => [day.registrations, day.firstGames]));
  return <><div className="mt-4 flex flex-wrap gap-4 text-xs text-ink/60"><span className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-sm bg-[#126A4A]/35" /> Регистрации</span><span className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-sm bg-[#126A4A]" /> Игроки с первой игрой</span><span>Максимум шкалы: {numberFormat.format(max)}</span></div><div className="mt-4 overflow-x-auto pb-2" role="img" aria-label="Сравнение регистраций и числа игроков с первой игрой по дням. Точные значения доступны в таблице ниже."><div className="flex h-48 items-end gap-1 border-b border-black/10" style={{ minWidth: Math.max(360, daily.length * 20) }}>{daily.map((day, index) => <div key={day.day} className="flex h-full min-w-0 flex-1 flex-col justify-end" title={`${day.day}: регистрации ${day.registrations}, игроки с первой игрой ${day.firstGames}`}><div className="flex h-40 items-end justify-center gap-px"><div className="w-2/5 rounded-t-sm bg-[#126A4A]/35" style={{ height: `${day.registrations / max * 100}%`, minHeight: day.registrations ? 2 : 0 }} /><div className="w-2/5 rounded-t-sm bg-[#126A4A]" style={{ height: `${day.firstGames / max * 100}%`, minHeight: day.firstGames ? 2 : 0 }} /></div><div className="h-7 pt-2 text-center text-[9px] tabular-nums text-ink/40">{index % Math.max(1, Math.ceil(daily.length / 10)) === 0 ? day.day.slice(5).split("-").reverse().join(".") : ""}</div></div>)}</div></div></>;
}
function safeContext(context: unknown): Array<[string, string]> {
  if (!context || typeof context !== "object" || Array.isArray(context)) return [];
  const labels: Record<string, string> = { source: "Источник", platform: "Платформа", screen: "Экран", step: "Шаг", sport: "Спорт", action: "Действие", outcome: "Результат", status: "Статус", searchType: "Тип поиска" };
  return Object.entries(context).filter(([key, value]) => key in labels && ["string", "number", "boolean"].includes(typeof value)).slice(0, 6).map(([key, value]) => [labels[key], String(value).slice(0, 80)]);
}
